#!/bin/sh

echo "Running all tests..."

./run names_sorted_100.txt runtest q >> output.txt
./run names_sorted_1000.txt runtest q >> output.txt
./run names_sorted_10000.txt runtest q >> output.txt
./run names_sorted_100000.txt runtest q >> output.txt
#./run names_sorted_1000000.txt runtest q >> output.txt
./run names_unsorted_100.txt runtest q >> output.txt
./run names_unsorted_1000.txt runtest q >> output.txt
./run names_unsorted_10000.txt runtest q >> output.txt
./run names_unsorted_100000.txt runtest q >> output.txt
#./run names_unsorted_1000000.txt runtest q >> output.txt
